services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  react-app:
    build:
      context: ./frontend

  tensorflow_serving:
    image: dongquannguyen/hateful_mls
    build:
      context: ./backend