services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8501:8501"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  tensorflow_serving:
    image: tensorflow/serving
    volumes:
      - ./models:/models
    command: >
      --model_config_file=/models/models.config \
      --model_config_file_poll_wait_seconds=60
